sudo: required

services:
  - docker
  - xvfb
before_install:
  - echo $HOST_IP_ADDRESS
  - docker build -f dockerfile.dev -t sgaloyan/node-auth_test .

script:
  - docker run sgaloyan/node-auth_test

deploy:
  # deploy master to production
  - provider: script
    script: $HOST_IP_ADDRESS
    on:
      branch: master


  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: $SECRET_ACCESS_KEY
  region: us-east-2
  app: "node-auth"
  env: "NodeAuth-env"
  bucket_name: "elasticbeanstalk-us-east-2-299932691470"
  on: master
