sudo: required

services:
  - docker

before_install:
  - docker build -f dockerfile.dev -t sgaloyan/node_auth_dev .

script:
  - docker run sgaloyan/node_auth_dev

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_ACCESS_KEY
  region: us-east-2
  app: "node-auth-docker"
  env: "NodeAuthDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-299932691470"
  on: master
