sudo: required

services:
  - docker

before_install:
  - docker build -f dockerfile.dev -t sgaloyan/node_auth_test .

script:
  - docker run sgaloyan/node_auth_test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_ACCESS_KEY
  region: us-east-2
  app: "node_auth"
  env: "NodeAuth-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-299932691470"
  on: master

after_success:
  - docker stop container sgaloyan/node_auth_test
  - docker build -f dockerfile -t sgaloyan/node_auth .
  - docker run sgaloyan/node_auth
