sudo: required

services:
  - docker

before_install:
  - docker build -f dockerfile -t sgaloyan/node_auth .

script:
  - docker run sgaloyan/node_auth

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_ACCESS_KEY
  region: us-east-2
  app: "node_auth"
  env: "NodeAuth-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-299932691470"
  on: master
