sudo: required

services:
  - docker
  - xvfb
before_install:
  - echo $HOST_IP_ADDRESS
  - docker build -f dockerfile.dev -t sgaloyan/node-auth_test .

script:
  - docker run sgaloyan/node-auth_test

deploy:
  # deploy master to production
  # /sbin/ip route|awk '/default/ { print $3 }'
  - provider: script
    script: $HOST_IP_ADDRESS
    on:
      branch: master

