sudo: required

services:
  - docker

before_install:
  - docker build -f dockerfile.dev -t sgaloyan/node_auth_dev .

script:
  - docker run sgaloyan/node_auth_dev

after_success:
  - docker stop container sgaloyan/node_auth_dev
  - docker build -f Dockerfile -t sgaloyan/node-auth .
  - docker run sgaloyan/node-auth

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_ACCESS_KEY
  region: us-east-2
  app: "node-auth"
  env: "NodeAuth-env"
  bucket_name: "s3-node-auth"
  on: master

